version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_rodrigastronomia
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rodrigastronomia
      MYSQL_USER: rodri
      MYSQL_PASSWORD: rodri123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./rodrigastronomia
    container_name: backend_rodrigastronomia
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./rodrigastronomia:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: rodri
      DB_PASS: rodri123

  frontend:
    build: ./rodrigastronomia-vue
    container_name: frontend_rodrigastronomia
    ports:
      - "5173:5173"
    volumes:
      - ./rodrigastronomia-vue:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - backend

volumes:
  mysql_data:
